[package]
name = "rustjs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.130"
tokio = { version = "1.17", features = ["full"] }
clap = { version = "3.1.11", features = ["derive"] }